DROP TABLE IF EXISTS AccountData;
DROP TABLE IF EXISTS FriendGroup;
DROP TABLE IF EXISTS Game;
DROP TABLE IF EXISTS OnlineStatus;
DROP TABLE IF EXISTS Profile;
DROP TABLE IF EXISTS UserTable;
CREATE TABLE AccountData(accountDataId serial PRIMARY KEY, eMail VARCHAR(255), hashedPassword VARCHAR(255));
CREATE TABLE FriendGroup(friendGroupId serial PRIMARY KEY, friendGroupName VARCHAR(255), lastFavouriteGame VARCHAR(255), friendProfileMappingId BIGINT);
CREATE TABLE Game(gameId serial PRIMARY KEY, gameName VARCHAR(255), gameLogoURL VARCHAR(500), startTime TIMESTAMP, endtime TIMESTAMP, rating int);
CREATE TABLE OnlineStatus(onlineStatusId serial PRIMARY KEY, status VARCHAR(255));
CREATE TABLE Profile(profileId serial PRIMARY KEY, onlineStatusMappingId BIGINT, profileName VARCHAR(255), profileImageURL VARCHAR(500), gamesMappingId BIGINT, friendProfileMappingId BIGINT);
CREATE TABLE UserTable(userId serial PRIMARY KEY, accountDataMappingId BIGINT, profileMappingId BIGINT);