# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install dependencies
        working-directory: ./frontend/gamingDate
        run: flutter pub get
      - name: Analyze project source
        working-directory: ./frontend/gamingDate
        run: flutter analyze
      - name: Run tests
        working-directory: ./frontend/gamingDate
        run: flutter test
